language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - DB=sqlite BRANCH=stable8
  - DB=postgresql BRANCH=stable8
  - DB=mysql BRANCH=stable8

matrix:
  allow_failures:
    - php: hhvm

install:
  # install ocdev
  - sudo apt-get -y install python3-jinja2 python3-setuptools
  - sudo easy_install3 requests
  - sudo easy_install3 ocdev
  # set up postgresql
  - createuser -U travis -s oc_autotest
  # set up mysql
  - mysql -e 'create database oc_autotest;'
  - mysql -u root -e "CREATE USER 'oc_autotest'@'localhost';"
  - mysql -u root -e "grant all on oc_autotest.* to 'oc_autotest'@'localhost';"
  # install owncloud
  - cd ..
  - ocdev setup core --dir owncloud --branch $BRANCH --no-history
  - cd owncloud
  - ocdev ci $DB
  # enable wiki
  - mv ../wiki apps/
  - php -f console.php app:enable wiki

before_script:
  - cd apps/wiki

script:
  - phpunit -c phpunit.xml
  - phpunit -c phpunit.integration.xml
